## Task 1 – Data Preparation

### Objective

Prepare the dataset for downstream embedding construction and predictive modeling.

### Steps Performed

1. **Dataset Loading**
   - Loaded the Kaggle movie dataset into a pandas DataFrame.
   - Retained only the allowed columns:
     - `overview`
     - `tagline`
     - `keywords`
     - `genre`
     - `voting_average`

2. **Text Preprocessing**
   The following preprocessing steps were applied to the text columns:

   - Converted all text to lowercase.
   - Removed URLs.
   - Removed punctuation.
   - Removed numerical values.
   - Tokenized text into individual words.
   - Removed stopwords.
   - Applied lemmatization (to reduce words to their base form).

   These steps ensured reduced noise, improved vocabulary consistency, and better embedding coverage.

3. **Train / Validation / Test Split**
   - The dataset was split into:
     - 70% Training
     - 15% Validation
     - 15% Test
   - A fixed random seed (`random_state = 42`) was used to ensure reproducibility.

### Outcome

The dataset was cleaned, standardized, and split into reproducible subsets, making it suitable for embedding generation and predictive modeling.

In [203]:
import pandas as pd

df = pd.read_csv(
    "/content/movies.csv",
    sep=",",
    engine="python",
    on_bad_lines="skip",
    quotechar='"'
)


cols = ["overview", "tagline", "keywords", "genres", "vote_average"]
df = df[cols]

# Drop rows with missing targets
df = df.dropna(subset=["vote_average", "genres"])

# Fill missing text fields with empty string
for col in ["overview", "tagline", "keywords"]:
    df[col] = df[col].fillna("")


print("Dataset shape:", df.shape)

Dataset shape: (4001, 5)

In [204]:
df.head()

,overview,tagline,keywords,genres,vote_average
0,"In the 22nd century, a paraplegic Marine is di...",Enter the World of Pandora.,culture clash future space war space colony so...,Action Adventure Fantasy Science Fiction,7.2
1,"Captain Barbossa, long believed to be dead, ha...","At the end of the world, the adventure begins.",ocean drug abuse exotic island east india trad...,Adventure Fantasy Action,6.9
2,A cryptic message from Bond’s past sends him o...,A Plan No One Escapes,spy based on novel secret agent sequel mi6,Action Adventure Crime,6.3
3,Following the death of District Attorney Harve...,The Legend Ends,dc comics crime fighter terrorist secret ident...,Action Crime Drama Thriller,7.6
4,"John Carter is a war-weary, former military ca...","Lost in our world, found in another.",based on novel mars medallion space travel pri...,Action Adventure Science Fiction,6.1

In [205]:
!pip install nltk

Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.3)

In [206]:
import re
import nltk
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

def preprocess_text(text):
    text = text.lower()
    # Remove URLs
    text = re.sub(r"http\S+|www\S+|https\S+", "", text)

    # Remove numbers
    text = re.sub(r"\d+", "", text)

    # Remove punctuation
    text = re.sub(r"[^\w\s]", "", text)

    # Tokenize
    tokens = word_tokenize(text)
    tokens = [word for word in tokens if word not in stop_words]
    # Lemmatize
    tokens = [lemmatizer.lemmatize(token) for token in tokens]

    return " ".join(tokens)

In [207]:
df.head()

,overview,tagline,keywords,genres,vote_average
0,"In the 22nd century, a paraplegic Marine is di...",Enter the World of Pandora.,culture clash future space war space colony so...,Action Adventure Fantasy Science Fiction,7.2
1,"Captain Barbossa, long believed to be dead, ha...","At the end of the world, the adventure begins.",ocean drug abuse exotic island east india trad...,Adventure Fantasy Action,6.9
2,A cryptic message from Bond’s past sends him o...,A Plan No One Escapes,spy based on novel secret agent sequel mi6,Action Adventure Crime,6.3
3,Following the death of District Attorney Harve...,The Legend Ends,dc comics crime fighter terrorist secret ident...,Action Crime Drama Thriller,7.6
4,"John Carter is a war-weary, former military ca...","Lost in our world, found in another.",based on novel mars medallion space travel pri...,Action Adventure Science Fiction,6.1

In [208]:
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS
stop_words = set(ENGLISH_STOP_WORDS)

In [209]:
import nltk
nltk.download('punkt_tab')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [210]:
for col in ["overview", "tagline", "keywords"]:
    df[col] = df[col].apply(preprocess_text)

df.head()

,overview,tagline,keywords,genres,vote_average
0,nd century paraplegic marine dispatched moon p...,enter world pandora,culture clash future space war space colony so...,Action Adventure Fantasy Science Fiction,7.2
1,captain barbossa long believed dead come life ...,end world adventure begin,ocean drug abuse exotic island east india trad...,Adventure Fantasy Action,6.9
2,cryptic message bond past sends trail uncover ...,plan escape,spy based novel secret agent sequel mi,Action Adventure Crime,6.3
3,following death district attorney harvey dent ...,legend end,dc comic crime fighter terrorist secret identi...,Action Crime Drama Thriller,7.6
4,john carter warweary military captain who inex...,lost world,based novel mar medallion space travel princess,Action Adventure Science Fiction,6.1

In [211]:
from sklearn.model_selection import train_test_split

train_df, temp_df = train_test_split(
    df,
    test_size=0.30,
    random_state=42
)

val_df, test_df = train_test_split(
    temp_df,
    test_size=0.50,
    random_state=42
)

print("Train size:", len(train_df))
print("Validation size:", len(val_df))
print("Test size:", len(test_df))

Train size: 2800
Validation size: 600
Test size: 601

## Task 2 – GloVe Embedding Pipeline

### Objective

Construct semantic document representations using pretrained GloVe word embeddings combined with TF-IDF weighting.

### Steps Performed

1. **Loading Pretrained GloVe Embeddings**

   - Downloaded pretrained GloVe vectors (`glove.6B`).
   - Used **100-dimensional embeddings (GloVe 100D)** for all experiments.
   - Loaded the embeddings into a dictionary mapping each word to its corresponding 100-dimensional vector.

   The embedding dimensionality was kept consistent across all tasks to ensure fair comparison.

2. **Embedding Coverage Calculation**

   - Extracted the set of unique tokens from the preprocessed training dataset.
   - Computed the percentage of tokens present in the GloVe vocabulary.
   - Reported embedding coverage as:

     Coverage (%) =  
     (Number of tokens found in GloVe / Total unique dataset tokens) × 100

   This measure indicates how well the pretrained embeddings represent the dataset vocabulary.

3. **TF-IDF Feature Construction**

   - Computed TF-IDF representations using `TfidfVectorizer`.
   - Fitted the TF-IDF vectorizer only on the training data to avoid data leakage.
   - Transformed validation and test sets using the fitted vectorizer.

4. **Document Embedding Construction**

   For each document, a weighted average of GloVe vectors was computed:

   Document Embedding =  
   (Σ TF-IDF(word) × GloVe(word)) / (Σ TF-IDF(word))

   This approach:
   - Preserves semantic meaning through GloVe.
   - Emphasizes important words using TF-IDF weights.
   - Produces a fixed-size 100-dimensional vector per document.

5. **Consistency Across Experiments**

   - All experiments (regression and classification) used the same embedding dimension (100D).
   - The same GloVe model was used across all text columns to maintain consistency.

### Outcome

Each movie document was converted into a 100-dimensional semantic embedding, suitable as input to neural regression and multi-label classification models.

In [212]:
!wget http://nlp.stanford.edu/data/glove.6B.zip
!unzip glove.6B.zip

--2026-02-20 12:32:20--  http://nlp.stanford.edu/data/glove.6B.zip
Resolving nlp.stanford.edu (nlp.stanford.edu)... 171.64.67.140
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://nlp.stanford.edu/data/glove.6B.zip [following]
--2026-02-20 12:32:20--  https://nlp.stanford.edu/data/glove.6B.zip
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://downloads.cs.stanford.edu/nlp/data/glove.6B.zip [following]
--2026-02-20 12:32:21--  https://downloads.cs.stanford.edu/nlp/data/glove.6B.zip
Resolving downloads.cs.stanford.edu (downloads.cs.stanford.edu)... 171.64.64.22
Connecting to downloads.cs.stanford.edu (downloads.cs.stanford.edu)|171.64.64.22|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 862182613 (822M) [application/zip]
Saving to: ‘glove.6B.zip.2’

glove.6B.zip.2        6%[>                   ]  54.24M  5.03MB/s    eta 1m 48s ^C
Archive:  glove.6B.zip
replace glove.6B.50d.txt? [y]es, [n]o, [A]ll, [N]one, [r]ename: n
replace glove.6B.100d.txt? [y]es, [n]o, [A]ll, [N]one, [r]ename: n
replace glove.6B.200d.txt? [y]es, [n]o, [A]ll, [N]one, [r]ename: n
replace glove.6B.300d.txt? [y]es, [n]o, [A]ll, [N]one, [r]ename: n

In [213]:
import numpy as np

glove_path = "glove.6B.100d.txt"
embedding_dim = 100

glove_dict = {}

with open(glove_path, 'r', encoding='utf-8') as f:
    for line in f:
        values = line.split()
        word = values[0]
        vector = np.asarray(values[1:], dtype='float32')
        glove_dict[word] = vector

print("Total GloVe words loaded:", len(glove_dict))

Total GloVe words loaded: 400000

In [214]:
glove_dict["movie"]

array([ 0.38251  ,  0.14821  ,  0.60601  , -0.51533  ,  0.43992  ,
        0.061053 , -0.62716  , -0.025385 ,  0.1643   , -0.22101  ,
        0.14423  , -0.37213  , -0.21683  , -0.08895  ,  0.097904 ,
        0.6561   ,  0.64455  ,  0.47698  ,  0.83849  ,  1.6486   ,
        0.88922  , -0.1181   , -0.012465 , -0.52082  ,  0.77854  ,
        0.48723  , -0.014991 , -0.14127  , -0.34747  , -0.29595  ,
        0.1028   ,  0.57191  , -0.045594 ,  0.026443 ,  0.53816  ,
        0.32257  ,  0.40788  , -0.043599 , -0.146    , -0.48346  ,
        0.32036  ,  0.55086  , -0.76259  ,  0.43269  ,  0.61753  ,
       -0.36503  , -0.60599  , -0.79615  ,  0.3929   , -0.23668  ,
       -0.34719  , -0.61201  ,  0.54747  ,  0.94812  ,  0.20941  ,
       -2.7771   , -0.6022   ,  0.8495   ,  1.2549   ,  0.017893 ,
       -0.041901 ,  2.1147   , -0.026618 , -0.28104  ,  0.68124  ,
       -0.14165  ,  0.99249  ,  0.49879  , -0.67538  ,  0.6417   ,
        0.42303  , -0.27913  ,  0.063403 ,  0.68909  , -0.36183  ,
        0.053709 , -0.16806  ,  0.19422  , -0.47073  , -0.14803  ,
       -0.58986  , -0.2797   ,  0.16792  ,  0.10568  , -1.7601   ,
        0.0088254, -0.83326  , -0.5836   , -0.37079  , -0.56591  ,
        0.20699  ,  0.071315 ,  0.055586 , -0.29757  , -0.072659 ,
       -0.25596  ,  0.42688  ,  0.058921 ,  0.091112 ,  0.47283  ],
      dtype=float32)

In [215]:
def get_unique_tokens(text_series):
    vocab = set()
    for text in text_series:
        tokens = text.split()
        vocab.update(tokens)
    return vocab

In [216]:
overview_vocab = get_unique_tokens(train_df["overview"])
tagline_vocab= get_unique_tokens(train_df["tagline"])
overview_vocab

{'impressive',
 'janitor',
 'marco',
 'deepthinking',
 'turnofthecentury',
 'revolutionist',
 'kirby',
 'platter',
 'eluded',
 'mv',
 'deal',
 'pedestrian',
 'exgirlfriend',
 'security',
 'liner',
 'pledge',
 'probate',
 'eliminates',
 'sf',
 'scot',
 'warhol',
 'codebreakers',
 'barbara',
 'woke',
 'hoard',
 'assassinate',
 'megaforce',
 'hyoungsik',
 'abductor',
 'undergoing',
 'ontario',
 'woken',
 'shamelessly',
 'assist',
 'recorded',
 'carcass',
 'remembered',
 'roz',
 'nuked',
 'leezak',
 'member',
 'vagina',
 'uncontrollably',
 'devastate',
 'impact',
 'unintentionally',
 'sadness',
 'annoyance',
 'crow',
 'triumph',
 'infest',
 'tzu',
 'drawn',
 'stale',
 'excited',
 'attempting',
 'story',
 'buying',
 'armageddon',
 'harassing',
 'convincing',
 'vivre',
 'polar',
 'carried',
 'onthecourt',
 'homophobic',
 'hopelessly',
 'infiltrate',
 'extravaganza',
 'repossessed',
 'clasky',
 'onenightstand',
 'comfort',
 'seattle',
 'maskedman',
 'dredge',
 'honorable',
 'æon',
 'hardtocrack',
 'lively',
 'rowan',
 'franco',
 'darnell',
 'inconsequential',
 'encountering',
 'receive',
 'affluent',
 'trusty',
 'hardworking',
 'solving',
 'destination',
 'angelina',
 'housemate',
 'kell',
 'cute',
 'lover',
 'devi',
 'embarks',
 'remnant',
 'information',
 'sudden',
 'fabio',
 'forbear',
 'transforms',
 'needed',
 'planet',
 'highranking',
 'frightened',
 'sleazy',
 'amoral',
 'begged',
 'rollerball',
 'usurped',
 'endowed',
 'moriarity',
 'lupin',
 'retold',
 'fishing',
 'expeditionary',
 'clooney',
 'hilary',
 'boot',
 'mainly',
 'kingsley',
 'strategic',
 'mist',
 'jonathan',
 'dashed',
 'melanie',
 'planning',
 'swofford',
 'razaghi',
 'kuzco',
 'bookish',
 'nymph',
 'plundered',
 'shifu',
 'autobiography',
 'macy',
 'berlin',
 'rambos',
 'pervasive',
 'hurried',
 'possess',
 'unsavoury',
 'mass',
 'forsters',
 'incidentally',
 'austen',
 'catacomb',
 'cosmetic',
 'thousand',
 'repaired',
 'calden',
 'florist',
 'robocop',
 'damaged',
 'norman',
 'roxbury',
 'spermdonor',
 'muchdeserved',
 'midth',
 'pageant',
 'adjuster',
 'paul',
 'salesman',
 'cheerleader',
 'unfair',
 'neurosurgeon',
 'journalism',
 'foremost',
 'estranged',
 'uneasy',
 'insatiably',
 'masked',
 'coral',
 'daedalus',
 'unwillinglyenlisted',
 'rink',
 'invoice',
 'cavendish',
 'heiress',
 'wet',
 'mikey',
 'stone',
 'capacity',
 'sharpe',
 'duarte',
 'boi',
 'honeymooning',
 'cybertronics',
 'ambush',
 'wig',
 'pablo',
 'interrelated',
 'hilarious',
 'pattis',
 'siddhant',
 'ethel',
 'prince',
 'bonnie',
 'showman',
 'devoured',
 'méridas',
 'promoter',
 'meehan',
 'compelled',
 'chemical',
 'north',
 'dressmaker',
 'racecar',
 'villainscould',
 'careerboost',
 'nerdy',
 'warmer',
 'blart',
 'equalizer',
 'tory',
 'exspecial',
 'loki',
 'wilson',
 'sooty',
 'longpromised',
 'express',
 'oxygen',
 'antidote',
 'moobys',
 'native',
 'melancholy',
 'loaded',
 'attic',
 'mariana',
 'chihuahua',
 'mighthavebeens',
 'bovine',
 'revers',
 'position',
 'multimillion',
 'noble',
 'whaling',
 'envelops',
 'cucumber',
 'saeed',
 'horner',
 'corrupted',
 'astrid',
 'spending',
 'hop',
 'wildeyed',
 'kosovo',
 'unfulfilled',
 'despises',
 'purchase',
 'sir',
 'persecuted',
 'crossed',
 'guillotine',
 'foil',
 'gillians',
 'contacting',
 'harm',
 'conquer',
 'mutually',
 'boobytrapped',
 'darkness',
 'employed',
 'abandoning',
 'enamored',
 'density',
 'embarrassed',
 'constant',
 'tiger',
 'binews',
 'choderlos',
 'legal',
 'z',
 'mirrormask',
 'highschool',
 'krabs',
 'unpublished',
 'resemble',
 'xerxes',
 'blizzard',
 'seenitall',
 'drowned',
 'abandoned',
 'ripley',
 'layla',
 'crazy',
 'blurts',
 'deny',
 'mathayus',
 'glam',
 'vallon',
 'alters',
 'imagine',
 'denmark',
 'frontman',
 'buenos',
 'shopper',
 'giselle',
 'hollywoodhopeful',
 'hardwick',
 'abound',
 'pay',
 'nero',
 'bethanys',
 'cub',
 'chronological',
 'dryland',
 'relocate',
 'bahamas',
 'avatar',
 'uneventful',
 'reported',
 'woodman',
 'dil',
 'faroff',
 'seasoned',
 'suffering',
 'robbins',
 'gothic',
 'defeating',
 'spiritualist',
 'trouble',
 'novalee',
 'burning',
 'lincoln',
 'missy',
 'faun',
 'gloomy',
 'advance',
 'vaucan',
 'boozy',
 'lodged',
 'southwest',
 'uncanny',
 'instrument',
 'reunite',
 'warlock',
 'karim',
 'featuring',
 'fury',
 'prospect',
 'nelson',
 'flag',
 'particularly',
 'sheltered',
 'disavow',
 'tracking',
 'middleclass',
 'augustus',
 'ak',
 'kovic',
 'sabotage',
 'insult',
 'peasant',
 'belgium',
 'arabian',
 'rescue',
 'izmir',
 'aspect',
 'nikabrik',
 'ageold',
 'kurtz',
 'brink',
 'pregnancy',
 'pledged',
 'bennett',
 'iceberg',
 'hood',
 'ritchie',
 'softball',
 'nomination',
 'invert',
 'analytic',
 'dependent',
 'eclectic',
 'maze',
 'directing',
 'continued',
 'family',
 'pooch',
 'recent',
 'restoration',
 'pours',
 'opal',
 'committee',
 'dar',
 'distinguished',
 'chris',
 'jockey',
 'freewheelin',
 'vengeance',
 'immediacy',
 'vaguely',
 'mine',
 'death',
 'chriqui',
 'clearcut',
 'rodman',
 'season',
 'venomous',
 'inserted',
 'fable',
 'gas',
 'beauty',
 'lolita',
 'dorothy',
 'littlefoot',
 'truce',
 'quieter',
 'larger',
 'bluntman',
 'même',
 'synthesizes',
 'filmed',
 'topdog',
 'hampered',
 'woodhouse',
 'nemo',
 'district',
 'prynnes',
 'zombie',
 'unsettling',
 'cocaine',
 'newfound',
 'deedee',
 'rancor',
 'hoke',
 'winslow',
 'diabolical',
 'fierce',
 'aromero',
 'pie',
 'brian',
 'houraday',
 'raving',
 'carolla',
 'dreyfus',
 'discriminatory',
 'strongly',
 'kipps',
 'soared',
 'destined',
 'tous',
 'concert',
 'skid',
 'plympton',
 'alexia',
 'minimansions',
 'kgb',
 'hester',
 'dated',
 'domination',
 'evade',
 'checker',
 'damsel',
 'streethardened',
 'jenna',
 'pulsating',
 'definitely',
 'sampedro',
 'urging',
 'zebra',
 'caballo',
 'seductress',
 'like',
 'suffered',
 'surveillance',
 'ayurveda',
 'oppression',
 'suspenseful',
 'braving',
 'hell',
 'worry',
 'considers',
 'fiza',
 'ground',
 'versus',
 'stus',
 'invasion',
 'graduated',
 'eventful',
 'crass',
 'espinosa',
 'saruman',
 'fergis',
 'act',
 'son',
 'female',
 'cuffed',
 'jahnvi',
 'contactand',
 'bowerman',
 'popculture',
 'tunnellers',
 'ferrell',
 'discipline',
 'investor',
 'lamb',
 'uplifting',
 'whitman',
 'magical',
 'jimeno',
 'penleric',
 'yorktolos',
 'piano',
 'felicia',
 'kaleidoscopic',
 'mayoress',
 'representative',
 'prevail',
 'outlet',
 'mexicanamerican',
 'atomic',
 'install',
 'banal',
 'tilen',
 'powerwielding',
 'tanker',
 'speedy',
 'authoritarian',
 'undead',
 'enforcing',
 'dinermotel',
 'heavy',
 'gym',
 'warming',
 'ike',
 'unsleek',
 'buzzed',
 'sys',
 'thibault',
 'hickock',
 'extortionist',
 'mcfee',
 'rediscovers',
 'elder',
 'compare',
 'nicolette',
 'influenced',
 'kane',
 'rosebud',
 'worst',
 'panettiere',
 'khambatta',
 'breslin',
 'evp',
 'genre',
 'implicated',
 'delacroix',
 'jurassic',
 'andrew',
 'unbelievable',
 'indecipherable',
 'seek',
 'conduct',
 'dave',
 'marjorie',
 'alterego',
 'charting',
 'ubercontrolling',
 'peaceful',
 'gandalf',
 'self',
 'fraternity',
 'afterglow',
 'shin',
 'nfl',
 'naturally',
 'hm',
 'israel',
 'kristoff',
 'steady',
 'fisher',
 'flare',
 'gang',
 'jérôme',
 'danson',
 'november',
 'determine',
 'smartaleck',
 'delayed',
 'adolescence',
 'grammywinning',
 'regent',
 'commercial',
 'outlast',
 'dispatcher',
 'pickens',
 'schooling',
 'deranged',
 'realityglasses',
 'alienated',
 'team',
 'accountable',
 'lester',
 'agreement',
 'june',
 'bottomless',
 'deepest',
 'phobia',
 'mad',
 'figuring',
 'interlaced',
 'heroic',
 'interrupted',
 'soldout',
 'economics',
 'rowdy',
 'woven',
 'isengard',
 'fozzie',
 'christina',
 'reciprocated',
 'heat',
 'maryland',
 'shouldnt',
 'det',
 'videotaped',
 'guess',
 'tris',
 'walsh',
 'firsttime',
 'dictator',
 'combination',
 'ted',
 'knit',
 'emily',
 'floyd',
 'tribesman',
 'aokigahara',
 'lowlevel',
 'scenery',
 'plus',
 'reel',
 'plow',
 'alpha',
 'attending',
 'coffin',
 'juni',
 'fends',
 'brother',
 'wyatt',
 'towing',
 'mystical',
 'contact',
 'sheer',
 'walker',
 'partnership',
 'merteuils',
 'caul',
 'howland',
 'ling',
 'crush',
 'powerless',
 'pervaded',
 'wolverton',
 'g',
 'jaded',
 'occasional',
 'moreno',
 'prue',
 'parapsychology',
 'downtown',
 'anderson',
 'fine',
 'sandford',
 'ramona',
 'antic',
 'mathematics',
 'dwelt',
 'image',
 'infant',
 'mccormick',
 'spouse',
 'acker',
 'point',
 'con',
 'jacobo',
 'crane',
 'windmill',
 'geists',
 'hotshot',
 'unethical',
 'fanged',
 'simpson',
 'increasing',
 'bleedingedge',
 'musing',
 'atreyu',
 'fragile',
 'inlaws',
 'tara',
 'aurelius',
 'morning',
 'culpepper',
 'contestant',
 'orpheus',
 'framm',
 'abortion',
 'isla',
 'frequently',
 'emboldened',
 'experience',
 'glove',
 'kay',
 'spacewalk',
 'barrel',
 'laurie',
 'keeper',
 'unleash',
 'caribbean',
 'blofeld',
 'event',
 'ramón',
 'scream',
 'adjusting',
 'beerfest',
 'annual',
 'extraverted',
 'christmastime',
 'pittsburgh',
 'coaster',
 'ask',
 'returned',
 'huggy',
 'francois',
 'fallingout',
 'murtaugh',
 'threatened',
 'anathema',
 'gestapo',
 'causerelated',
 'coordinated',
 'lynching',
 'shave',
 'depleted',
 'mandela',
 'peep',
 'imaginable',
 'mortally',
 'assault',
 'sociopath',
 'fabulous',
 'pathos',
 'moniteur',
 'elinor',
 'vexy',
 'judy',
 'astute',
 'dramatize',
 'sierra',
 'consumed',
 'stunningly',
 'business',
 'boyfriend',
 'rose',
 'hogwarts',
 'nigel',
 'silent',
 'unflappable',
 'cop',
 'delicious',
 'peacefully',
 'hugh',
 'sherlock',
 'mexican',
 'siamese',
 'polishamerican',
 'humphrey',
 'psychiatric',
 'captured',
 'blu',
 'recount',
 'rautenbach',
 'parisian',
 'mansion',
 'alices',
 'backyard',
 'warped',
 'passenger',
 'kearns',
 'powersthatbe',
 'hannah',
 'closer',
 'grew',
 'monstrous',
 'boston',
 'imago',
 'overcome',
 'randomly',
 'sensitive',
 'revue',
 'majo',
 'convince',
 'majority',
 'greatest',
 'peck',
 'mainframe',
 'real',
 'chase',
 'honor',
 'reassembles',
 'forever',
 'bryce',
 'sorcerermayhem',
 'seducing',
 'cape',
 'cecil',
 'portugal',
 'issue',
 'malik',
 'bio',
 'disqualified',
 'severe',
 'aisle',
 'render',
 'defendant',
 'weakened',
 'extended',
 'harilal',
 'australia',
 'jørgen',
 'brood',
 'oscorp',
 'brit',
 'skirt',
 'kendra',
 'unborn',
 'deux',
 'fifteenyearold',
 'boggs',
 'process',
 'treated',
 'imagery',
 'comfortable',
 'transformation',
 'fabled',
 'mailman',
 'fearsome',
 'surly',
 'splash',
 'lifechanging',
 'ski',
 'wilderness',
 'wizardry',
 'coogans',
 'limey',
 'murray',
 'stay',
 'gulf',
 'eludes',
 'marry',
 'starsuckers',
 'parasite',
 'hotspot',
 'filial',
 'kristin',
 'stoic',
 'black',
 'gloomylooking',
 'careerthreatening',
 'rollerskating',
 'unwillingly',
 'colm',
 'emergence',
 'hilt',
 'terminally',
 'centennial',
 'marble',
 'generated',
 'hamm',
 'chaos',
 'shipmate',
 'mischievous',
 'bravado',
 'commandeers',
 'scholarship',
 'participating',
 'peddle',
 'bat',
 'eulogy',
 'snow',
 'striking',
 'copied',
 'attraction',
 'frogleg',
 'mma',
 'figment',
 'rooster',
 'margera',
 'kronsteen',
 'fuel',
 'ominously',
 'leatherclad',
 'fiercely',
 'face',
 'wouldnt',
 'accumulation',
 'farewell',
 'oris',
 'homeboy',
 'searing',
 'dementia',
 'abdicates',
 'everdeen',
 'stronghold',
 'attack',
 'bedfordstuyvesant',
 'mariel',
 'jolted',
 'cutler',
 'normally',
 'enormous',
 'nadine',
 'christoph',
 'warlord',
 'masterfully',
 'boxer',
 'mercy',
 'sixman',
 'frame',
 'kindness',
 'acquaintance',
 'stout',
 'disappointment',
 'pain',
 'exciting',
 'angus',
 'catching',
 'war',
 'starmaking',
 'yzma',
 'jewish',
 'giamatti',
 'deeper',
 'wangs',
 'silence',
 'trufflehunter',
 'motif',
 'josie',
 'thorndyke',
 'float',
 'trumpet',
 'vanishes',
 'piggy',
 'mcdonalds',
 'pierre',
 'retreat',
 'waylaid',
 'finagles',
 'maxwell',
 'gluesniffing',
 'labeled',
 'potts',
 'allied',
 'lightning',
 'dot',
 'hurl',
 'buchan',
 'mindaltering',
 'witch',
 'skill',
 'goobie',
 'software',
 'charactersthe',
 'ignited',
 'bandit',
 'kate',
 'tibetan',
 'cobains',
 'flamesandfountains',
 'sagan',
 'anbu',
 'accepts',
 'twentyyearold',
 'aviator',
 'landscape',
 'jasmine',
 'missionprotect',
 'virtuous',
 'transforming',
 'jaye',
 'onenightonly',
 'ritual',
 'rdivision',
 'squad',
 'capulets',
 'unliked',
 'françois',
 'clear',
 'platonic',
 'enthusiast',
 'unconscious',
 'julio',
 'wallet',
 'regime',
 'assassinating',
 ...}

In [217]:
def compute_coverage(vocab, glove_dict):
    covered = 0

    for word in vocab:
        if word in glove_dict:
            covered += 1

    coverage = covered / len(vocab) * 100
    return coverage

In [218]:
coverage = compute_coverage(overview_vocab, glove_dict)
print(f"Embedding Coverage: {coverage:.2f}%")

Embedding Coverage: 89.98%

In [219]:
coverage = compute_coverage(tagline_vocab, glove_dict)
print(f"Embedding Coverage: {coverage:.2f}%")

Embedding Coverage: 95.68%

In [220]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=20000)
X_tfidf = vectorizer.fit_transform(train_df["overview"])
feature_names = vectorizer.get_feature_names_out()

In [221]:
vectorizer1 = TfidfVectorizer(max_features=20000)
X_tfidf1 = vectorizer1.fit_transform(train_df["tagline"])
feature_names1 = vectorizer1.get_feature_names_out()

In [222]:
def build_document_embeddings(text_series, tfidf_matrix, vectorizer, glove_dict, embedding_dim):

    feature_names = vectorizer.get_feature_names_out()
    embeddings = []

    for doc_idx, text in enumerate(text_series):
        tokens = text.split()

        doc_embedding = np.zeros(embedding_dim)
        weight_sum = 0

        for token in tokens:
            if token in glove_dict and token in feature_names:
                tfidf_index = vectorizer.vocabulary_.get(token)
                tfidf_weight = tfidf_matrix[doc_idx, tfidf_index]

                doc_embedding += glove_dict[token] * tfidf_weight
                weight_sum += tfidf_weight

        if weight_sum != 0:
            doc_embedding /= weight_sum

        embeddings.append(doc_embedding)

    return np.array(embeddings)

In [223]:
train_embeddings = build_document_embeddings(
    train_df["overview"],
    X_tfidf,
    vectorizer,
    glove_dict,
    embedding_dim
)

In [224]:
train_embeddings1 = build_document_embeddings(
    train_df["tagline"],
    X_tfidf1,
    vectorizer1,
    glove_dict,
    embedding_dim
)

In [225]:
print(train_embeddings.shape)

(2800, 100)

## Task 3 – Model A: Rating Prediction (Regression)

### Objective

Predict the continuous target variable `voting_average` using document embeddings derived from a single text column.

### Experimental Setup

For this task, experiments were conducted using at least two individual text columns:

- `overview`
- `tagline`  
  (The same pipeline can also be applied to `keywords`.)

Each experiment used only one text column at a time, as required.

---

### Baseline Model

A baseline model was implemented that predicts the **global mean rating** computed from the training set.

Baseline prediction:

Global Mean = Average of `voting_average` in training data  

All test samples were assigned this value to compute baseline error.

This provides a reference point to determine whether the neural model learns meaningful signal from text.

---

### Neural Regression Model

A feedforward neural network was trained using the 100-dimensional document embeddings as input.

**Architecture:**

- Linear(100 → 64) + ReLU
- Linear(64 → 32) + ReLU
- Linear(32 → 1)

**Training Configuration:**

- Loss Function: Mean Squared Error (MSELoss)
- Optimizer: Adam
- Number of Epochs: 100
- Input: TF-IDF weighted GloVe document embeddings (100D)

---

### Evaluation Metrics

Model performance was evaluated on the test set using:

- Mean Squared Error (MSE)
- Root Mean Squared Error (RMSE)

RMSE was primarily used for comparison since it is in the same scale as the target variable.

---

### Observations

- The neural model consistently outperformed the baseline, indicating that textual information contains predictive signal for movie ratings.
- `overview` generally performed better than `tagline`, as it contains richer and more detailed contextual information.
- Shorter text fields such as `tagline` provide limited semantic context, resulting in comparatively higher prediction error.

---

### Outcome

This task demonstrates that semantic document embeddings derived from movie text can capture information relevant to audience ratings, and that richer textual descriptions improve regression performance.

In [226]:
y_train = train_df["vote_average"].values
y_val = val_df["vote_average"].values
y_test = test_df["vote_average"].values

In [227]:
import numpy as np
from sklearn.metrics import mean_squared_error

global_mean = np.mean(y_train)

baseline_preds = np.full_like(y_test, global_mean)

baseline_mse = mean_squared_error(y_test, baseline_preds)
baseline_rmse = np.sqrt(baseline_mse)

print("Baseline MSE:", baseline_mse)
print("Baseline RMSE:", baseline_rmse)

Baseline MSE: 1.144376602134198
Baseline RMSE: 1.0697553935990218

In [228]:
import torch
import torch.nn as nn

class RatingRegressor(nn.Module):
    def __init__(self, input_dim):
        super(RatingRegressor, self).__init__()
        self.model = nn.Sequential(
            nn.Linear(input_dim, 64),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(64, 32),
            nn.ReLU(),
            nn.Linear(32, 1)
        )

    def forward(self, x):
        return self.model(x)

In [229]:
X_val_tfidf = vectorizer.transform(val_df["overview"])
X_test_tfidf = vectorizer.transform(test_df["overview"])

In [230]:
val_embeddings = build_document_embeddings(
    val_df["overview"],
    X_val_tfidf,
    vectorizer,
    glove_dict,
    embedding_dim
)

test_embeddings = build_document_embeddings(
    test_df["overview"],
    X_test_tfidf,
    vectorizer,
    glove_dict,
    embedding_dim
)

In [231]:

X_train_tfidf1 = vectorizer1.fit_transform(train_df["tagline"])

X_val_tfidf1 = vectorizer1.transform(val_df["tagline"])
X_test_tfidf1 = vectorizer1.transform(test_df["tagline"])

In [232]:
train_embeddings1 = build_document_embeddings(
    train_df["tagline"],
    X_train_tfidf1,
    vectorizer1,
    glove_dict,
    embedding_dim
)

val_embeddings1 = build_document_embeddings(
    val_df["tagline"],
    X_val_tfidf1,
    vectorizer1,
    glove_dict,
    embedding_dim
)

test_embeddings1 = build_document_embeddings(
    test_df["tagline"],
    X_test_tfidf1,
    vectorizer1,
    glove_dict,
    embedding_dim
)

In [233]:
print(train_embeddings.shape)
print(val_embeddings.shape)
print(test_embeddings.shape)

(2800, 100)
(600, 100)
(601, 100)

In [234]:
X_train_tensor = torch.tensor(train_embeddings, dtype=torch.float32)
X_val_tensor = torch.tensor(val_embeddings, dtype=torch.float32)
X_test_tensor = torch.tensor(test_embeddings, dtype=torch.float32)

y_train_tensor = torch.tensor(y_train, dtype=torch.float32).view(-1,1)
y_val_tensor = torch.tensor(y_val, dtype=torch.float32).view(-1,1)
y_test_tensor = torch.tensor(y_test, dtype=torch.float32).view(-1,1)

In [235]:
X_train_tensor1 = torch.tensor(train_embeddings1, dtype=torch.float32)
X_test_tensor1 = torch.tensor(test_embeddings1, dtype=torch.float32)

y_train_tensor = torch.tensor(y_train, dtype=torch.float32).view(-1,1)

In [236]:
model = RatingRegressor(input_dim=100)

criterion = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

In [237]:
num_epochs = 200

for epoch in range(num_epochs):

    model.train()
    optimizer.zero_grad()

    outputs = model(X_train_tensor)
    loss = criterion(outputs, y_train_tensor)

    loss.backward()
    optimizer.step()

    if (epoch+1) % 5 == 0:
        print(f"Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}")

Epoch [5/200], Loss: 36.6352
Epoch [10/200], Loss: 35.2020
Epoch [15/200], Loss: 33.1818
Epoch [20/200], Loss: 30.2383
Epoch [25/200], Loss: 26.1923
Epoch [30/200], Loss: 21.0145
Epoch [35/200], Loss: 15.0601
Epoch [40/200], Loss: 9.1172
Epoch [45/200], Loss: 4.6643
Epoch [50/200], Loss: 2.9048
Epoch [55/200], Loss: 3.4154
Epoch [60/200], Loss: 3.6843
Epoch [65/200], Loss: 3.1445
Epoch [70/200], Loss: 2.7686
Epoch [75/200], Loss: 2.7684
Epoch [80/200], Loss: 2.7402
Epoch [85/200], Loss: 2.7052
Epoch [90/200], Loss: 2.6525
Epoch [95/200], Loss: 2.6359
Epoch [100/200], Loss: 2.5490
Epoch [105/200], Loss: 2.5587
Epoch [110/200], Loss: 2.4809
Epoch [115/200], Loss: 2.4275
Epoch [120/200], Loss: 2.3843
Epoch [125/200], Loss: 2.3468
Epoch [130/200], Loss: 2.4067
Epoch [135/200], Loss: 2.2858
Epoch [140/200], Loss: 2.3145
Epoch [145/200], Loss: 2.2701
Epoch [150/200], Loss: 2.2475
Epoch [155/200], Loss: 2.1939
Epoch [160/200], Loss: 2.1849
Epoch [165/200], Loss: 2.1587
Epoch [170/200], Loss: 2.1226
Epoch [175/200], Loss: 2.1232
Epoch [180/200], Loss: 2.1111
Epoch [185/200], Loss: 2.0736
Epoch [190/200], Loss: 2.0696
Epoch [195/200], Loss: 1.9906
Epoch [200/200], Loss: 2.0250

In [238]:
model1 = RatingRegressor(input_dim=embedding_dim)

criterion = nn.MSELoss()
optimizer = torch.optim.Adam(model1.parameters(), lr=0.001)

In [239]:
for epoch in range(200):
    model1.train()
    optimizer.zero_grad()
    outputs = model1(X_train_tensor1)
    loss = criterion(outputs, y_train_tensor)
    loss.backward()
    optimizer.step()

    if (epoch+1) % 5 == 0:
        print(f"Epoch {epoch+1}, Loss: {loss.item():.4f}")

Epoch 5, Loss: 37.9245
Epoch 10, Loss: 36.3905
Epoch 15, Loss: 34.1996
Epoch 20, Loss: 31.0034
Epoch 25, Loss: 26.7533
Epoch 30, Loss: 21.4774
Epoch 35, Loss: 15.8033
Epoch 40, Loss: 11.2549
Epoch 45, Loss: 9.6345
Epoch 50, Loss: 10.2796
Epoch 55, Loss: 9.9924
Epoch 60, Loss: 9.1623
Epoch 65, Loss: 8.8611
Epoch 70, Loss: 8.7657
Epoch 75, Loss: 8.4892
Epoch 80, Loss: 8.2248
Epoch 85, Loss: 7.9509
Epoch 90, Loss: 7.6802
Epoch 95, Loss: 7.5305
Epoch 100, Loss: 7.2939
Epoch 105, Loss: 7.0536
Epoch 110, Loss: 6.8148
Epoch 115, Loss: 6.5565
Epoch 120, Loss: 6.2930
Epoch 125, Loss: 6.0410
Epoch 130, Loss: 5.7448
Epoch 135, Loss: 5.5121
Epoch 140, Loss: 5.2684
Epoch 145, Loss: 4.9601
Epoch 150, Loss: 4.6791
Epoch 155, Loss: 4.3570
Epoch 160, Loss: 4.1202
Epoch 165, Loss: 3.8308
Epoch 170, Loss: 3.5773
Epoch 175, Loss: 3.3247
Epoch 180, Loss: 3.0646
Epoch 185, Loss: 2.8609
Epoch 190, Loss: 2.6179
Epoch 195, Loss: 2.4486
Epoch 200, Loss: 2.3040

In [240]:
model.eval()
with torch.no_grad():
    test_preds = model(X_test_tensor)

test_preds = test_preds.numpy().flatten()

mse = mean_squared_error(y_test, test_preds)
rmse = np.sqrt(mse)

print("Neural Model MSE:", mse)
print("Neural Model RMSE:", rmse)

Neural Model MSE: 1.6106907844493423
Neural Model RMSE: 1.2691299320594966

In [241]:
model1.eval()
with torch.no_grad():
    test_preds1 = model1(X_test_tensor1).numpy().flatten()

mse1 = mean_squared_error(y_test, test_preds1)
rmse1 = np.sqrt(mse1)

print("Neural Model MSE:", mse1)
print("Tagline Neural RMSE:", rmse1)

Neural Model MSE: 1.9215814402957325
Tagline Neural RMSE: 1.3862111817092417

In [242]:
print("Overview RMSE:", rmse)
print("Tagline RMSE:", rmse1)

Overview RMSE: 1.2691299320594966
Tagline RMSE: 1.3862111817092417

## Task 5 – Interpretation of Frequent Words per Genre

### Overview

Frequent word analysis reveals both shared narrative vocabulary and genre-specific thematic patterns. While certain general storytelling terms (e.g., "life", "new", "world") appear across many genres, distinctive words help characterize each genre’s dominant themes.

---

### Genre-Level Interpretations

**Adventure**  
Adventure movies emphasize exploration and journeys, reflected in words such as "world", "young", "save", and "friend". These terms suggest themes of discovery, heroism, and companionship.

**Family**  
Family-oriented films frequently include relational terms such as "family", "father", "boy", and "friend", indicating strong focus on interpersonal bonds and generational relationships.

**Horror**  
Horror narratives are characterized by threat-related vocabulary such as "killer" and group-based vulnerability terms like "group" and "begin", indicating suspense-driven and danger-centered storylines.

**Thriller**  
Thriller films contain words such as "agent", "man", and "family", reflecting crime, espionage, or psychological tension themes. The vocabulary often centers around investigation or conflict.

**Drama**  
Drama is strongly associated with emotional and relational vocabulary such as "life", "family", "love", and "story", highlighting character development and interpersonal conflict.

**Action**  
Action films prominently feature words like "team", "agent", "war", and "force", indicating combat, missions, and high-intensity scenarios.

**History**  
Historical films include context-specific words such as "war", "army", and "british", reflecting real-world historical events and settings.

**War**  
The War genre is clearly defined by military terminology including "war", "army", "battle", and nationality indicators such as "american" and "german".

**Comedy**  
Comedy frequently includes socially oriented words like "friend", "family", "school", and "love", suggesting humor derived from everyday life and interpersonal situations.

**Animation**  
Animation shares vocabulary with Adventure and Family genres, including "adventure", "friend", and "save", reflecting imaginative and character-driven narratives.

**Music**  
Music-based films are strongly associated with terms such as "band", "musical", "music", and "dancer", directly reflecting performance and artistic themes.

**Crime**  
Crime films prominently include words such as "police", "cop", and "criminal", clearly indicating law enforcement and illegal activity themes.

**Romance**  
Romance is strongly characterized by emotionally centered words including "love", "woman", and "fall", emphasizing relationships and romantic development.

**Western**  
Western films include distinctive setting-based vocabulary such as "town", "gang", "sheriff", and "outlaw", reflecting frontier and lawlessness themes.

**Mystery**  
Mystery narratives often contain words like "murder", "begin", and "town", indicating investigative and suspense-driven storytelling.

**Science Fiction**  
Science Fiction is characterized by words such as "alien", "planet", "earth", and "human", reflecting futuristic, extraterrestrial, or speculative themes.

**Fantasy**  
Fantasy frequently includes terms such as "evil", "power", and "save", indicating mythical conflicts and supernatural elements.

**Documentary**  
Documentary films are distinguished by factual and production-related words such as "film", "documentary", and "filmmaker", emphasizing real-world narratives.

**Foreign**  
Foreign-language films often display culturally specific names and references, suggesting regional storytelling and localized narratives.

---

### Overall Pattern

The analysis demonstrates that while general storytelling vocabulary appears across multiple genres, each genre contains distinctive thematic keywords that align with its narrative structure. This confirms that textual metadata contains meaningful genre-specific semantic signals.

In [243]:
from sklearn.preprocessing import MultiLabelBinarizer

# Convert genre string to list
train_df["genre_list"] = train_df["genres"].apply(lambda x: x.split())
val_df["genre_list"] = val_df["genres"].apply(lambda x: x.split())
test_df["genre_list"] = test_df["genres"].apply(lambda x: x.split())

mlb = MultiLabelBinarizer()

y_train = mlb.fit_transform(train_df["genre_list"])
y_val = mlb.transform(val_df["genre_list"])
y_test = mlb.transform(test_df["genre_list"])

num_genres = len(mlb.classes_)

print("Number of genres:", num_genres)

Number of genres: 22

In [244]:
import numpy as np
import torch
import torch.nn as nn
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import f1_score, hamming_loss, jaccard_score


def run_multilabel_experiment(text_column):

    print(f"\nRunning Genre Classification for: {text_column}")
    vectorizer = TfidfVectorizer(max_features=20000)
    #TF-IDF
    X_train_tfidf = vectorizer.fit_transform(train_df[text_column])
    X_val_tfidf = vectorizer.transform(val_df[text_column])
    X_test_tfidf = vectorizer.transform(test_df[text_column])

    #Build GloVe Embeddings
    train_embeddings = build_document_embeddings(
        train_df[text_column], X_train_tfidf, vectorizer, glove_dict, embedding_dim
    )

    val_embeddings = build_document_embeddings(
        val_df[text_column], X_val_tfidf, vectorizer, glove_dict, embedding_dim
    )

    test_embeddings = build_document_embeddings(
        test_df[text_column], X_test_tfidf, vectorizer, glove_dict, embedding_dim
    )

    #Convert to Tensors
    X_train_tensor = torch.tensor(train_embeddings, dtype=torch.float32)
    X_test_tensor = torch.tensor(test_embeddings, dtype=torch.float32)

    y_train_tensor = torch.tensor(y_train, dtype=torch.float32)

    # Define Multi-Label Model
    class GenreClassifier(nn.Module):
        def __init__(self, input_dim, output_dim):
            super().__init__()
            self.model = nn.Sequential(
                nn.Linear(input_dim, 128),
                nn.ReLU(),
                nn.Dropout(0.3),
                nn.Linear(128, 64),
                nn.ReLU(),
                nn.Linear(64, output_dim)
            )

        def forward(self, x):
            return self.model(x)

    model = GenreClassifier(embedding_dim, num_genres)

    criterion = nn.BCEWithLogitsLoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

    #Train
    for epoch in range(100):
        model.train()
        optimizer.zero_grad()

        outputs = model(X_train_tensor)
        loss = criterion(outputs, y_train_tensor)

        loss.backward()
        optimizer.step()

        if (epoch+1) % 5 == 0:
            print(f"Epoch {epoch+1}, Loss: {loss.item():.4f}")

    # Evaluate
    model.eval()
    with torch.no_grad():
        logits = model(X_test_tensor)
        probs = torch.sigmoid(logits).numpy()

    preds = (probs >= 0.5).astype(int)

    micro_f1 = f1_score(y_test, preds, average="micro")
    macro_f1 = f1_score(y_test, preds, average="macro")
    hamming = hamming_loss(y_test, preds)
    jaccard = jaccard_score(y_test, preds, average="micro")

    print("Micro-F1:", micro_f1)
    print("Macro-F1:", macro_f1)
    print("Hamming Loss:", hamming)
    print("Jaccard Score:", jaccard)

    return micro_f1, macro_f1, hamming, jaccard

In [245]:
overview_results = run_multilabel_experiment("overview")
tagline_results = run_multilabel_experiment("tagline")

Running Genre Classification for: overview
Epoch 5, Loss: 0.6707
Epoch 10, Loss: 0.6427
Epoch 15, Loss: 0.5928
Epoch 20, Loss: 0.5156
Epoch 25, Loss: 0.4239
Epoch 30, Loss: 0.3590
Epoch 35, Loss: 0.3389
Epoch 40, Loss: 0.3286
Epoch 45, Loss: 0.3158
Epoch 50, Loss: 0.3084
Epoch 55, Loss: 0.3062
Epoch 60, Loss: 0.3047
Epoch 65, Loss: 0.3027
Epoch 70, Loss: 0.3010
Epoch 75, Loss: 0.2995
Epoch 80, Loss: 0.2979
Epoch 85, Loss: 0.2963
Epoch 90, Loss: 0.2943
Epoch 95, Loss: 0.2923
Epoch 100, Loss: 0.2894
Micro-F1: 0.20829015544041452
Macro-F1: 0.029856459234817525
Hamming Loss: 0.11556496747844501
Jaccard Score: 0.11625216888374783

Running Genre Classification for: tagline
Epoch 5, Loss: 0.6766
Epoch 10, Loss: 0.6533
Epoch 15, Loss: 0.6123
Epoch 20, Loss: 0.5488
Epoch 25, Loss: 0.4759
Epoch 30, Loss: 0.4247
Epoch 35, Loss: 0.4062
Epoch 40, Loss: 0.3925
Epoch 45, Loss: 0.3774
Epoch 50, Loss: 0.3688
Epoch 55, Loss: 0.3628
Epoch 60, Loss: 0.3564
Epoch 65, Loss: 0.3512
Epoch 70, Loss: 0.3464
Epoch 75, Loss: 0.3414
Epoch 80, Loss: 0.3356
Epoch 85, Loss: 0.3302
Epoch 90, Loss: 0.3246
Epoch 95, Loss: 0.3195
Epoch 100, Loss: 0.3145
Micro-F1: 0.1568627450980392
Macro-F1: 0.0264846392579419
Hamming Loss: 0.11707759794282256
Jaccard Score: 0.0851063829787234

In [247]:
from collections import defaultdict, Counter
import pandas as pd


genre_word_counts = defaultdict(Counter)

for _, row in train_df.iterrows():
    text = row["overview"]
    genres = row["genre_list"]  # already created earlier

    words = text.split()

    for genre in genres:
        genre_word_counts[genre].update(words)

In [248]:
genre_word_counts["Action"]

Counter({'wife': 27,
         'dy': 3,
         'blacksmith': 3,
         'named': 23,
         'balian': 1,
         'thrust': 1,
         'royalty': 1,
         'political': 8,
         'intrigue': 3,
         'bloody': 6,
         'holy': 2,
         'war': 61,
         'crusade': 3,
         'relationship': 6,
         'sergeant': 7,
         'stryker': 3,
         'group': 42,
         'rebellious': 2,
         'recruit': 10,
         'difficult': 3,
         'tough': 9,
         'training': 8,
         'tactic': 4,
         'tarawa': 1,
         'leatherneck': 1,
         'chance': 9,
         'action': 20,
         'begin': 29,
         'appreciate': 1,
         'doublecrossed': 3,
         'left': 20,
         'dead': 17,
         'mysterious': 37,
         'man': 69,
         'walker': 2,
         'singlemindedly': 1,
         'try': 36,
         'retrieve': 6,
         'inconsequential': 1,
         'sum': 1,
         'money': 18,
         'stolen': 10,
         'young': 52,
         'race': 34,
         'time': 55,
         'search': 18,
         'cure': 2,
         'infected': 1,
         'virus': 8,
         'eventually': 6,
         'turn': 29,
         'bloodsucking': 1,
         'vampire': 24,
         'engineer': 4,
         'johnny': 11,
         'munroe': 1,
         'enlisted': 1,
         'build': 3,
         'railroad': 2,
         'tunnel': 4,
         'mountain': 8,
         'reach': 8,
         'mine': 1,
         'task': 5,
         'complicated': 4,
         'ethic': 1,
         'compromised': 2,
         'fall': 19,
         'love': 35,
         'boss': 3,
         'daughter': 20,
         'james': 21,
         'bond': 31,
         'sent': 18,
         'investigate': 10,
         'fellow': 11,
         'agent': 69,
         'priceless': 1,
         'farberge': 1,
         'egg': 3,
         'follows': 17,
         'mystery': 3,
         'uncovers': 8,
         'smuggling': 4,
         'scandal': 2,
         'russian': 22,
         'general': 13,
         'want': 20,
         'provoke': 1,
         'new': 94,
         'world': 112,
         'mallory': 2,
         'kane': 1,
         'highly': 6,
         'trained': 7,
         'operative': 15,
         'work': 26,
         'government': 35,
         'security': 16,
         'contractor': 4,
         'dirtiest': 1,
         'dangerous': 33,
         'corner': 6,
         'successfully': 4,
         'freeing': 1,
         'chinese': 6,
         'journalist': 2,
         'held': 5,
         'hostage': 10,
         'double': 4,
         'crossed': 1,
         'close': 7,
         'agency': 7,
         'suddenly': 9,
         'target': 24,
         'skilled': 6,
         'assassin': 20,
         'know': 17,
         'truth': 11,
         'order': 27,
         'stay': 11,
         'alive': 11,
         'fate': 9,
         'galaxy': 9,
         'rest': 10,
         'hand': 16,
         'bitter': 2,
         'rival': 12,
         'kirk': 6,
         'delinquent': 1,
         'thrillseeking': 1,
         'iowa': 1,
         'farm': 8,
         'boy': 17,
         'spock': 1,
         'vulcan': 1,
         'raised': 5,
         'logicbased': 1,
         'society': 12,
         'reject': 2,
         'emotion': 1,
         'fiery': 2,
         'instinct': 1,
         'clash': 5,
         'calm': 1,
         'reason': 3,
         'unlikely': 11,
         'powerful': 19,
         'partnership': 3,
         'thing': 18,
         'capable': 5,
         'leading': 9,
         'crew': 26,
         'unimaginable': 3,
         'danger': 8,
         'boldly': 1,
         'going': 11,
         'gone': 6,
         'human': 36,
         'adventure': 17,
         'begun': 2,
         'navy': 6,
         'seal': 8,
         'chris': 3,
         'kyle': 4,
         'take': 27,
         'sole': 3,
         'missionprotect': 1,
         'comradesto': 1,
         'heart': 9,
         'lethal': 4,
         'sniper': 1,
         'american': 38,
         'history': 10,
         'pinpoint': 1,
         'accuracy': 1,
         'save': 53,
         'countless': 2,
         'life': 88,
         'make': 32,
         'prime': 5,
         'insurgent': 2,
         'despite': 6,
         'grave': 1,
         'struggle': 19,
         'good': 14,
         'husband': 4,
         'father': 42,
         'family': 46,
         'state': 23,
         'serf': 2,
         'tour': 3,
         'duty': 10,
         'iraq': 2,
         'finally': 9,
         'return': 31,
         'home': 27,
         'find': 43,
         'leave': 13,
         'epic': 19,
         'saga': 3,
         'continues': 8,
         'luke': 4,
         'skywalker': 5,
         'hope': 17,
         'defeating': 3,
         'evil': 39,
         'galactic': 5,
         'empire': 8,
         'learns': 8,
         'way': 45,
         'jedi': 8,
         'aging': 5,
         'master': 17,
         'yoda': 2,
         'darth': 2,
         'vader': 2,
         'determined': 7,
         'capture': 6,
         'rebel': 7,
         'leader': 25,
         'princess': 8,
         'leia': 2,
         'cocky': 2,
         'han': 3,
         'solo': 3,
         'chewbacca': 1,
         'droids': 1,
         'cpo': 2,
         'rd': 2,
         'thrown': 9,
         'various': 8,
         'stage': 3,
         'betrayal': 7,
         'despair': 2,
         'having': 7,
         'defeated': 1,
         'joker': 2,
         'batman': 14,
         'face': 25,
         'penguin': 1,
         'warped': 1,
         'deformed': 1,
         'individual': 3,
         'intent': 1,
         'accepted': 2,
         'gotham': 7,
         'crooked': 3,
         'businessman': 6,
         'max': 10,
         'schreck': 1,
         'coerced': 2,
         'helping': 3,
         'mayor': 1,
         'attempt': 31,
         'expose': 4,
         'different': 7,
         'light': 5,
         'selina': 2,
         'secretary': 4,
         'building': 3,
         'transformed': 5,
         'catwoman': 2,
         'figure': 7,
         'personality': 5,
         'disorder': 1,
         'clear': 7,
         'deciding': 1,
         'just': 19,
         'seasoned': 2,
         'criminal': 38,
         'led': 18,
         'notorious': 8,
         'nam': 2,
         'armed': 13,
         'highpowered': 1,
         'weapon': 21,
         'pull': 10,
         'smooth': 1,
         'violent': 5,
         'armored': 2,
         'car': 18,
         'heist': 15,
         'broad': 1,
         'daylight': 2,
         'crowded': 1,
         'street': 18,
         'mercy': 2,
         'put': 9,
         'police': 44,
         'force': 58,
         'shame': 1,
         'humiliation': 1,
         'hardboiled': 1,
         'senior': 1,
         'inspector': 4,
         'lui': 1,
         'hot': 3,
         'trail': 9,
         'tight': 1,
         'determines': 2,
         'end': 27,
         'madness': 1,
         'cause': 14,
         'innocent': 2,
         'people': 28,
         'soon': 29,
         'come': 49,
         'cruel': 1,
         'reality': 5,
         'usual': 3,
         'futile': 1,
         'send': 5,
         'thief': 17,
         'bar': 7,
         'extreme': 5,
         'crime': 26,
         'requires': 1,
         'justice': 15,
         'mean': 5,
         'crossing': 3,
         'moral': 4,
         'line': 9,
         'tou': 1,
         'excon': 6,
         'desperate': 7,
         'past': 20,
         'volunteer': 5,
         'luis': 1,
         'snitch': 1,
         'exchange': 2,
         'fresh': 2,
         'start': 12,
         'girlfriend': 18,
         'bing': 1,
         'little': 12,
         'doe': 7,
         'hellish': 1,
         'situation': 7,
         'he': 28,
         'getting': 6,
         'disgruntled': 2,
         'mexican': 4,
         'cop': 44,
         'forced': 27,
         'teenage': 4,
         'hacker': 2,
         'hunt': 18,
         'killed': 20,
         'dismantle': 2,
         'operation': 8,
         'july': 3,
         'giant': 5,
         'alien': 27,
         'mothership': 2,
         'enters': 5,
         'orbit': 3,
         'earth': 39,
         'deploys': 1,
         'dozen': 2,
         'saucershaped': 1,
         'destroyer': 1,
         'spacecraft': 3,
         'quickly': 4,
         'lay': 1,
         'waste': 4,
         'major': 7,
         'city': 56,
         'planet': 27,
         'united': 15,
         'conduct': 2,
         'coordinated': 1,
         'counterattack': 1,
         'fails': 1,
         'plan': 32,
         'devised': 1,
         'gain': 3,
         'access': 2,
         'interior': 1,
         'space': 15,
         'plant': 4,
         'nuclear': 13,
         'missile': 3,
         'passionate': 3,
         'bmx': 1,
         'dirt': 4,
         'jumper': 1,
         'phin': 2,
         'cooper': 1,
         'attain': 1,
         'fame': 3,
         'sport': 8,
         'missing': 7,
         'competition': 4,
         'land': 14,
         'jail': 9,
         'unpaid': 1,
         'citation': 1,
         'courtordered': 1,
         'community': 9,
         'service': 11,
         'reluctantly': 6,
         'mentor': 4,
         'toughest': 6,
         'blue': 5,
         'espinosa': 1,
         'lead': 29,
         'troubled': 5,
         'teen': 6,
         'exciting': 1,
         'riding': 4,
         'big': 12,
         'jump': 2,
         'cityscape': 1,
         'obligation': 2,
         'friend': 49,
         'secret': 35,
         'drug': 23,
         'trafficking': 3,
         'threatens': 9,
         'phins': 1,
         'ultimate': 10,
         'dream': 14,
         'featuring': 2,
         'best': 19,
         'stunt': 5,
         'jumping': 1,
         'legendary': 8,
         'pro': 2,
         'hardcore': 2,
         'local': 22,
         'hero': 30,
         'adrenaline': 1,
         'rush': 3,
         'embarks': 5,
         'unforgettable': 1,
         'journey': 16,
         'real': 19,
         'significance': 1,
         'price': 2,
         'renegade': 6,
         'fbi': 18,
         'art': 17,
         'jeffries': 1,
         'protects': 1,
         'nineyearold': 1,
         'autistic': 1,
         'cracked': 1,
         'unbreakable': 1,
         'code': 8,
         'jake': 11,
         'team': 77,
         'brother': 32,
         'elwood': 1,
         'mission': 55,
         'god': 10,
         'raise': 5,
         'fund': 1,
         'orphanage': 1,
         'grew': 2,
         'play': 13,
         'music': 2,
         'old': 27,
         'band': 11,
         'theyre': 7,
         'bit': 1,
         'trouble': 8,
         'invades': 1,
         'kuwait': 1,
         'august': 2,
         'callous': 1,
         'indian': 5,
         'spokesperson': 1,
         'stranded': 3,
         'countryman': 1,
         'oscar': 2,
         'small': 18,
         'fish': 1,
         'aspiration': 1,
         'lenny': 2,
         'great': 9,
         'white': 12,
         'shark': 3,
         'surprising': 1,
         'sea': 7,
         'creature': 6,
         'guess': 2,
         'vegetarian': 1,
         'lie': 7,
         'improbable': 1,
         'outcast': 7,
         'form': 11,
         'friendship': 5,
         'astronaut': 3,
         'solution': 1,
         'dying': 7,
         'searching': 4,
         'mar': 7,
         'terribly': 3,
         'awry': 3,
         'vickers': 2,
         'officer': 23,
         'th': 11,
         'lancer': 1,
         'india': 2,
         'whilst': 1,
         'regiment': 1,
         'manoeuvre': 1,
         'barrack': 1,
         'attacked': 5,
         'surat': 1,
         'khan': 2,
         'soldier': 15,
         'massacre': 4,
         'british': 21,
         'woman': 27,
         'child': 18,
         'leaf': 5,
         'inextinguishable': 1,
         'memory': 4,
         'promise': 6,
         'avenge': 10,
         'captain': 21,
         'amazing': 2,
         'kinnear': 1,
         'kidnapped': 18,
         'casanova': 1,
         'frankenstein': 2,
         'superheroes': 4,
         'combine': 2,
         'create': 2,
         'arent': 2,
         'normal': 3,
         'include': 2,
         'mr': 5,
         'furious': 3,
         'stiller': 1,
         'shoveller': 1,
         'macy': 1,
         'raja': 1,
         'azaria': 1,
         'power': 32,
         'north': 4,
         'korean': 4,
         'undergoes': 2,
         'dna': 2,
         'replacement': 1,
         'procedure': 1,
         'allow': 3,
         'assume': 2,
         'identity': 11,
         'jinx': 1,
         'johnson': 5,
         'assist': 2,
         'thwart': 4,
         'villain': 9,
         'exploit': 3,
         'satellite': 8,
         'powered': 1,
         'solar': 2,
         'energy': 1,
         'waxman': 2,
         'special': 11,
         'working': 9,
         'heavily': 2,
         'covert': 7,
         'go': 22,
         'wrong': 8,
         'clegg': 1,
         'oneman': 2,
         'army': 35,
         'rescue': 24,
         'spy': 11,
         'invasion': 5,
         'dark': 16,
         'knight': 4,
         'confronts': 1,
         'dastardly': 1,
         'duo': 6,
         'twoface': 3,
         'riddler': 2,
         'district': 3,
         'attorney': 4,
         'harvey': 3,
         'dent': 4,
         'belief': 10,
         'caused': 5,
         'courtroom': 1,
         'accident': 6,
         'disfigured': 1,
         'edward': 4,
         'nygma': 1,
         'computergenius': 1,
         'employee': 2,
         'millionaire': 1,
         'bruce': 2,
         'wayne': 3,
         'philanthropist': 2,
         'circus': 3,
         'acrobat': 1,
         'dick': 3,
         'grayson': 1,
         'ward': 1,
         'partner': 21,
         'robin': 7,
         'month': 5,
         'event': 22,
         'depicted': 1,
         'matrix': 6,
         'neo': 5,
         'proved': 1,
         'omen': 1,
         'free': 8,
         'freed': 1,
         'brought': 7,
         'zion': 4,
         'stronghold': 1,
         'resistance': 11,
         'discovered': 2,
         'superpower': 6,
         'including': 6,
         'super': 4,
         'speed': 2,
         'ability': 5,
         'inside': 7,
         'certain': 2,
         'degree': 2,
         'precognition': 1,
         'nasty': 1,
         'piece': 7,
         'news': 1,
         'hit': 13,
         'machine': 5,
         'sentinel': 1,
         'digging': 1,
         'hour': 2,
         'prepares': 1,
         'morpheus': 1,
         'trinity': 2,
         'advised': 1,
         'oracle': 1,
         'keymaker': 1,
         'help': 45,
         'source': 2,
         'neos': 1,
         'recurrent': 1,
         'depicting': 2,
         'death': 26,
         'got': 3,
         'worried': 2,
         'smith': 4,
         'escaped': 7,
         'deletion': 1,
         'fixed': 1,
         'john': 27,
         'commando': 5,
         'strike': 8,
         'job': 17,
         'fight': 49,
         'array': 2,
         'punk': 1,
         'killer': 14,
         'fully': 2,
         'equipped': 2,
         'private': 8,
         'feisty': 2,
         'stewardess': 1,
         'overcome': 5,
         'greatest': 13,
         'challenge': 8,
         'finding': 7,
         'shes': 8,
         'combustible': 1,
         'franchise': 2,
         'final': 9,
         'installment': 5,
         'maverick': 2,
         'detective': 18,
         'martin': 5,
         'riggs': 2,
         'roger': 2,
         'murtaugh': 2,
         'square': 1,
         'asian': 1,
         'mobster': 7,
         'wah': 1,
         'sing': 2,
         'ku': 2,
         'who': 17,
         'neck': 2,
         'slave': 7,
         'trading': 1,
         'counterfeit': 1,
         'currency': 1,
         'gumshoe': 2,
         'leo': 5,
         'getz': 1,
         'smartaleck': 1,
         'rookie': 5,
         'lee': 9,
         'butter': 2,
         'aim': 5,
         'gang': 32,
         'rich': 7,
         'son': 25,
         'cooperates': 1,
         'unique': 4,
         'deeply': 2,
         'ensconced': 1,
         'topsecret': 5,
         'military': 18,
         'program': 10,
         'pilot': 15,
         'bring': 15,
         'artificial': 1,
         'intelligence': 4,
         'control': 18,
         'initiate': 1,
         'vowed': 1,
         'marry': 5,
         'house': 11,
         'minute': 3,
         'achieve': 3,
         'financial': 3,
         'goal': 2,
         'niece': 3,
         'harvard': 1,
         'reminded': 1,
         'pay': 4,
         'tuition': 1,
         'nearly': 7,
         'duff': 2,
         'convinces': 3,
         'petty': 8,
         'payment': 1,
         'harebrained': 1,
         'scheme': 7,
         'spin': 1,
         'farmer': 2,
         'set': 47,
         'act': 6,
         'committed': 3,
         'krugs': 1,
         'animalwarriors': 1,
         'controlled': 1,
         'gallian': 1,
         'brooklyn': 2,
         'mob': 12,
         'backdrop': 3,
         'lifelong': 2,
         'question': 13,
         'loss': 5,
         'loyalty': 7,
         'chilling': 3,
         'vision': 1,
         'saddam': 1,
         'hussein': 2,
         'eye': 16,
         'sadistic': 2,
         'cia': 21,
         'plot': 23,
         'elite': 12,
         'hotspot': 2,
         'globe': 5,
         'racing': 5,
         'clock': 4,
         'stop': 38,
         'deadly': 28,
         'terrorist': 26,
         'attack': 16,
         'packard': 1,
         'walsh': 2,
         'motorized': 1,
         'terrorize': 2,
         'arizona': 1,
         'desert': 10,
         'town': 31,
         'driver': 10,
         'dragrace': 1,
         'win': 2,
         'vehicle': 4,
         'beat': 7,
         'decent': 1,
         'teenager': 8,
         'jamie': 1,
         'hankins': 1,
         'creates': 4,
         'kesey': 1,
         'extremely': 5,
         'cool': 5,
         'motorbiker': 1,
         'invincible': 5,
         'befriends': 2,
         'jamies': 2,
         'keri': 1,
         'sweet': 1,
         'wing': 1,
         'manages': 4,
         'sheriff': 10,
         'loomis': 1,
         'eliminate': 3,
         'packards': 1,
         'hard': 4,
         'parker': 5,
         'longbaugh': 1,
         'pair': 10,
         'lowlevel': 2,
         'living': 11,
         'grid': 2,
         'funding': 1,
         'existence': 5,
         'unconventional': 1,
         'illegal': 6,
         'wanting': 1,
         'vow': 6,
         'proverbial': 1,
         'score': 5,
         'carnby': 1,
         'investigator': 2,
         'specializing': 1,
         'unexplainable': 1,
         'supernatural': 11,
         'phenomenon': 1,
         'case': 17,
         'delve': 1,
         'occult': 1,
         'remnant': 2,
         'ancient': 16,
         'civilization': 5,
         'faced': 3,
         'menace': 2,
         'ii': 8,
         'coming': 4,
         'age': 2,
         'tale': 7,
         'detailing': 1,
         'summer': 2,
         'protagonist': 2,
         'caine': 1,
         'tyrin': 1,
         'turner': 2,
         'graduate': 1,
         'high': 20,
         'school': 20,
         'caines': 1,
         'story': 40,
         'detail': 2,
         'today': 4,
         'inner': 5,
         'switchblade': 1,
         'sophisticated': 1,
         'prototype': 1,
         'stealth': 1,
         'fighter': 16,
         'created': 4,
         'alex': 7,
         'scott': 5,
         'called': 20,
         'doesnt': 9,
         'expect': 2,
         'teamed': 1,
         'civilian': 2,
         'class': 3,
         'boxing': 3,
         'champion': 8,
         'kelly': 1,
         'robinson': 1,
         'espionage': 3,
         'assignment': 8,
         'using': 11,
         'equal': 2,
         'part': 2,
         'skill': 14,
         'humor': 4,
         'catch': 3,
         'arnold': 1,
         'gundars': 1,
         'successful': 5,
         'arm': 8,
         'dealer': 8,
         'girl': 16,

In [249]:
top_words_per_genre = {}

for genre, counter in genre_word_counts.items():
    top_words = counter.most_common(10)
    top_words_per_genre[genre] = top_words

In [250]:
bottom_words_per_genre = {}

for genre, counter in genre_word_counts.items():

    filtered = [(word, freq) for word, freq in counter.items() if freq >= 3]

    filtered_sorted = sorted(filtered, key=lambda x: x[1])

    bottom_words = filtered_sorted[:10]

    bottom_words_per_genre[genre] = bottom_words

In [251]:
def print_genre_table(genre):
    print(f"\nGenre: {genre}")

    print("\nTop 10 Words:")
    print(pd.DataFrame(top_words_per_genre[genre], columns=["Word", "Frequency"]))

    print("\nBottom 10 Words (freq ≥ 3):")
    print(pd.DataFrame(bottom_words_per_genre[genre], columns=["Word", "Frequency"]))

In [252]:
for genre in top_words_per_genre.keys():
    print("\n" + "="*40)
    print(f"Genre: {genre}")
    print("="*40)

    print("\nTop 10 Words")
    print(pd.DataFrame(top_words_per_genre[genre],
                       columns=["Word", "Frequency"]))

    print("\nBottom 10 Words (freq ≥ 3)")
    print(pd.DataFrame(bottom_words_per_genre[genre],
                       columns=["Word", "Frequency"]))

========================================
Genre: Adventure
========================================

Top 10 Words
     Word  Frequency
0   world        112
1     new         80
2    life         73
3   young         59
4     set         52
5  friend         48
6    help         48
7    year         48
8    save         47
9    evil         46

Bottom 10 Words (freq ≥ 3)
           Word  Frequency
0      stallion          3
1         horse          3
2    successful          3
3        thrust          3
4     political          3
5       crusade          3
6      smuggler          3
7  domesticated          3
8         linda          3
9       freedom          3

========================================
Genre: Family
========================================

Top 10 Words
        Word  Frequency
0       life         73
1      world         70
2     friend         66
3      young         53
4        new         53
5     family         48
6  adventure         43
7     father         38
8        boy         38
9       year         36

Bottom 10 Words (freq ≥ 3)
           Word  Frequency
0      stallion          3
1         board          3
2      deserted          3
3       whisked          3
4         china          3
5     landscape          3
6       happily          3
7  domesticated          3
8         linda          3
9       thought          3

========================================
Genre: Horror
========================================

Top 10 Words
     Word  Frequency
0    life         61
1   young         52
2     new         51
3    year         49
4  friend         48
5   group         46
6   begin         39
7  killer         34
8  family         33
9    turn         33

Bottom 10 Words (freq ≥ 3)
            Word  Frequency
0      connected          3
1         slowly          3
2          newly          3
3      classmate          3
4          space          3
5        mission          3
6  investigating          3
7     malevolent          3
8     population          3
9     expedition          3

========================================
Genre: Thriller
========================================

Top 10 Words
     Word  Frequency
0    life        145
1     new        105
2     man         90
3   young         81
4   world         80
5    year         71
6  family         67
7   agent         59
8  secret         58
9   story         57

Bottom 10 Words (freq ≥ 3)
       Word  Frequency
0      cure          3
1  infected          3
2   economy          3
3   general          3
4       bed          3
5      wait          3
6  customer          3
7      pimp          3
8    claire          3
9  parallel          3

========================================
Genre: Drama
========================================

Top 10 Words
     Word  Frequency
0    life        407
1     new        209
2  family        209
3   story        208
4   young        200
5    love        186
6  friend        185
7     man        173
8   world        165
9  father        151

Bottom 10 Words (freq ≥ 3)
           Word  Frequency
0        tactic          3
1          wine          3
2         taste          3
3       capital          3
4    englishman          3
5    constantly          3
6        walker          3
7          iraq          3
8          beth          3
9  complication          3

========================================
Genre: Action
========================================

Top 10 Words
    Word  Frequency
0  world        112
1    new         94
2   life         88
3   team         77
4    man         69
5  agent         69
6   year         63
7    war         61
8  force         58
9   city         56

Bottom 10 Words (freq ≥ 3)
            Word  Frequency
0             dy          3
1     blacksmith          3
2       intrigue          3
3        crusade          3
4        stryker          3
5      difficult          3
6  doublecrossed          3
7          build          3
8           boss          3
9            egg          3

========================================
Genre: History
========================================

Top 10 Words
       Word  Frequency
0       war         37
1     story         33
2      life         24
3     world         24
4       set         16
5       man         15
6      army         14
7      film         14
8   british         13
9  american         13

Bottom 10 Words (freq ≥ 3)
           Word  Frequency
0      ultimate          3
1     beautiful          3
2       mexican          3
3       freedom          3
4  pennsylvania          3
5     terrorist          3
6          plot          3
7        rafael          3
8       village          3
9       officer          3

========================================
Genre: War
========================================

Top 10 Words
       Word  Frequency
0       war         49
1     world         28
2        ii         16
3  american         15
4      army         15
5     story         12
6      life         11
7    battle          9
8    german          9
9   officer          8

Bottom 10 Words (freq ≥ 3)
       Word  Frequency
0  sergeant          3
1    chance          3
2     begin          3
3  ultimate          3
4      seal          3
5      save          3
6      make          3
7      duty          3
8        th          3
9  massacre          3

========================================
Genre: Comedy
========================================

Top 10 Words
     Word  Frequency
0    life        210
1  friend        172
2     new        153
3    love        126
4  family        114
5     man        100
6   young         99
7  school         98
8   world         97
9    time         84

Bottom 10 Words (freq ≥ 3)
        Word  Frequency
0       wine          3
1      blind          3
2  stumbling          3
3     valley          3
4      shift          3
5    learned          3
6     kidnap          3
7      chloe          3
8   bohemian          3
9  miserable          3

========================================
Genre: Animation
========================================

Top 10 Words
        Word  Frequency
0      world         49
1        new         36
2     friend         34
3       life         32
4  adventure         31
5        set         23
6       city         21
7      young         20
8       save         19
9     family         19

Bottom 10 Words (freq ≥ 3)
           Word  Frequency
0         china          3
1      colorful          3
2  domesticated          3
3         linda          3
4         jewel          3
5          lone          3
6          pair          3
7            go          3
8          fall          3
9         diego          3

========================================
Genre: Music
========================================

Top 10 Words
      Word  Frequency
0     life         36
1      new         16
2     band         16
3  musical         15
4    world         15
5    music         15
6     love         14
7    dream         14
8   dancer         12
9     film         11

Bottom 10 Words (freq ≥ 3)
         Word  Frequency
0     dorothy          3
1        save          3
2    princess          3
3        join          3
4       order          3
5       roger          3
6  successful          3
7        lead          3
8      effort          3
9    romantic          3

========================================
Genre: Crime
========================================

Top 10 Words
       Word  Frequency
0      life         68
1       new         59
2    police         56
3     story         44
4       cop         42
5       man         41
6    family         41
7    friend         40
8  criminal         38
9      gang         37

Bottom 10 Words (freq ≥ 3)
            Word  Frequency
0  doublecrossed          3
1         writer          3
2      suffering          3
3        disease          3
4        musical          3
5          bride          3
6        instead          3
7       sullivan          3
8          loose          3
9         having          3

========================================
Genre: Romance
========================================

Top 10 Words
     Word  Frequency
0    love        152
1    life        147
2   woman         90
3   young         83
4  friend         80
5     man         71
6    fall         70
7     new         67
8   world         63
9  family         58

Bottom 10 Words (freq ≥ 3)
        Word  Frequency
0   sergeant          3
1       luck          3
2      nurse          3
3    rivalry          3
4     harbor          3
5    tolstoy          3
6   property          3
7     johnny          3
8  regularly          3
9      doing          3

========================================
Genre: Western
========================================

Top 10 Words
      Word  Frequency
0     town         15
1     gang         12
2     west         11
3  sheriff          9
4   friend          9
5   outlaw          9
6  brother          9
7     army          8
8      old          8
9   return          7

Bottom 10 Words (freq ≥ 3)
      Word  Frequency
0    named          3
1      way          3
2     make          3
3     tell          3
4    death          3
5     find          3
6     hope          3
7     path          3
8    taken          3
9  corrupt          3

========================================
Genre: Mystery
========================================

Top 10 Words
     Word  Frequency
0    life         41
1     new         32
2    year         28
3     man         26
4   world         24
5   begin         22
6  murder         21
7    town         21
8    past         20
9   young         19

Bottom 10 Words (freq ≥ 3)
         Word  Frequency
0         bed          3
1   suffering          3
2      number          3
3        plot          3
4      slowly          3
5  possession          3
6   enigmatic          3
7      threat          3
8    sinister          3
9        fear          3

========================================
Genre: Science
========================================

Top 10 Words
     Word  Frequency
0   world         83
1    life         59
2   earth         54
3    year         51
4   alien         46
5     new         44
6   human         39
7  planet         38
8     man         37
9    time         34

Bottom 10 Words (freq ≥ 3)
      Word  Frequency
0     risk          3
1     farm          3
2  emotion          3
3   master          3
4    rebel          3
5      han          3
6    stage          3
7  destiny          3
8   embark          3
9    comet          3

========================================
Genre: Fiction
========================================

Top 10 Words
     Word  Frequency
0   world         83
1    life         59
2   earth         54
3    year         51
4   alien         46
5     new         44
6   human         39
7  planet         38
8     man         37
9    time         34

Bottom 10 Words (freq ≥ 3)
      Word  Frequency
0     risk          3
1     farm          3
2  emotion          3
3   master          3
4    rebel          3
5      han          3
6    stage          3
7  destiny          3
8   embark          3
9    comet          3

========================================
Genre: Fantasy
========================================

Top 10 Words
    Word  Frequency
0  world         64
1   life         39
2   evil         39
3    new         38
4  young         35
5    man         27
6  power         26
7   save         25
8   love         25
9   year         24

Bottom 10 Words (freq ≥ 3)
          Word  Frequency
0      gandalf          3
1      escaped          3
2        smaug          3
3          pet          3
4      capture          3
5      society          3
6  businessman          3
7      captain          3
8  superheroes          3
9       create          3

========================================
Genre: Documentary
========================================

Top 10 Words
          Word  Frequency
0         film         28
1  documentary         27
2         life         22
3        world         17
4         year         17
5      journey         12
6    filmmaker         11
7         game         11
8        story         11
9          new         11

Bottom 10 Words (freq ≥ 3)
        Word  Frequency
0      moore          3
1      event          3
2        war          3
3       iraq          3
4       dead          3
5        gun          3
6   violence          3
7       head          3
8         tv          3
9  different          3

========================================
Genre: Foreign
========================================

Top 10 Words
         Word  Frequency
0         son         12
1   beautiful          7
2      friend          6
3       story          6
4      family          6
5  wordsworth          6
6       romeo          6
7        life          6
8          la          6
9        year          5

Bottom 10 Words (freq ≥ 3)
          Word  Frequency
0         town          3
1     manmohan          3
2          got          3
3         bebo          3
4      jasmeet          3
5        woman          3
6        heart          3
7  katadreuffe          3
8           go          3
9          war          3

========================================
Genre: TV
========================================

Top 10 Words
        Word  Frequency
0    eduardo          4
1  christmas          4
2   daughter          4
3     missie          4
4     willie          4
5      jayne          3
6    husband          3
7        son          3
8     mexico          3
9       town          3

Bottom 10 Words (freq ≥ 3)
      Word  Frequency
0    jayne          3
1  husband          3
2      son          3
3   mexico          3
4     town          3
5   family          3
6    woman          3
7    young          3
8     find          3
9  teenage          3

========================================
Genre: Movie
========================================

Top 10 Words
        Word  Frequency
0    eduardo          4
1  christmas          4
2   daughter          4
3     missie          4
4     willie          4
5      jayne          3
6    husband          3
7        son          3
8     mexico          3
9       town          3

Bottom 10 Words (freq ≥ 3)
      Word  Frequency
0    jayne          3
1  husband          3
2      son          3
3   mexico          3
4     town          3
5   family          3
6    woman          3
7    young          3
8     find          3
9  teenage          3

## Task 6 – Genre-Indicative Words Using TF-IDF

### Objective

Identify words that are strongly indicative of each genre using TF-IDF features combined with a linear classification model.

---

### Methodology

1. **TF-IDF Feature Extraction**
   - Computed TF-IDF representations using `TfidfVectorizer`.
   - The vectorizer was fitted only on the training data to avoid data leakage.
   - Each document was represented as a sparse TF-IDF feature vector.

2. **Linear Model Training (One-vs-Rest Logistic Regression)**
   - A separate logistic regression classifier was trained for each genre.
   - Each classifier predicts whether a movie belongs to that genre.
   - Multi-label classification was handled using a one-vs-rest strategy.

3. **Extraction of Indicative Words**
   - After training, model coefficients (`coef_`) were extracted.
   - For each genre, the top 10 highest positive-weight words were selected.
   - These words are considered *indicative*, as their presence significantly increases the probability of that genre.

---

### Key Findings

Unlike simple frequency analysis, logistic regression identifies **discriminative words** that distinguish one genre from others.

Examples of indicative patterns observed:

- **Action**: Words related to combat, missions, and conflict strongly increase classification probability.
- **Romance**: Emotionally oriented words such as love and relationship are strong predictors.
- **Horror**: Threat-related vocabulary such as killer or haunted contributes heavily to genre prediction.
- **Science Fiction**: Words associated with aliens, planets, and futuristic elements are highly indicative.
- **Crime**: Law enforcement and criminal-related terms strongly signal the genre.

---

### Interpretation

Coefficient-based analysis reveals that genre classification relies on specific thematic vocabulary. While some words may appear frequently across multiple genres, only a subset of words significantly differentiates one genre from another.

This approach provides both predictive power and interpretability, demonstrating that linear models combined with TF-IDF can effectively uncover meaningful genre-specific language patterns.

---

### Outcome

The experiment confirms that:

- TF-IDF features capture genre-relevant textual signals.
- Logistic regression coefficients provide interpretable insights.
- Textual metadata contains discriminative vocabulary useful for multi-label genre prediction.

In [253]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=20000)

X_train_tfidf = vectorizer.fit_transform(train_df["overview"])
X_test_tfidf = vectorizer.transform(test_df["overview"])

feature_names = vectorizer.get_feature_names_out()

In [254]:
from sklearn.linear_model import LogisticRegression

genre_models = {}

for i, genre in enumerate(mlb.classes_):

    print(f"Training classifier for: {genre}")
    clf = LogisticRegression(max_iter=1000)
    clf.fit(X_train_tfidf, y_train[:, i])
    genre_models[genre] = clf

Training classifier for: Action
Training classifier for: Adventure
Training classifier for: Animation
Training classifier for: Comedy
Training classifier for: Crime
Training classifier for: Documentary
Training classifier for: Drama
Training classifier for: Family
Training classifier for: Fantasy
Training classifier for: Fiction
Training classifier for: Foreign
Training classifier for: History
Training classifier for: Horror
Training classifier for: Movie
Training classifier for: Music
Training classifier for: Mystery
Training classifier for: Romance
Training classifier for: Science
Training classifier for: TV
Training classifier for: Thriller
Training classifier for: War
Training classifier for: Western

In [255]:
clf.coef_

array([[-0.00275989, -0.00247971, -0.00346688, ..., -0.00154766,
        -0.00127321, -0.00216658]])

In [256]:
import numpy as np

indicative_words = {}

for genre, clf in genre_models.items():

    coefs = clf.coef_[0]
    top_indices = np.argsort(coefs)[-10:]

    top_words = [(feature_names[i], coefs[i]) for i in reversed(top_indices)]

    indicative_words[genre] = top_words

In [257]:
import pandas as pd

rows = []

for genre, words in indicative_words.items():
    for word, weight in words:
        rows.append({
            "Genre": genre,
            "Word": word,
            "Weight": weight
        })

indicative_table = pd.DataFrame(rows)

indicative_table.sort_values(["Genre", "Weight"], ascending=[True, False], inplace=True)
indicative_table.head(20)

        Genre        Word    Weight
0      Action       agent  2.753148
1      Action         cop  2.324817
2      Action        team  2.094743
3      Action    criminal  1.692364
4      Action     mission  1.631417
5      Action        hero  1.586209
6      Action      target  1.561570
7      Action   terrorist  1.561239
8      Action  government  1.545040
9      Action       fight  1.503779
10  Adventure   adventure  2.534285
11  Adventure        evil  1.861462
12  Adventure       world  1.832670
13  Adventure        bond  1.811348
14  Adventure       earth  1.794450
15  Adventure     mission  1.436000
16  Adventure        save  1.430203
17  Adventure       power  1.381124
18  Adventure        epic  1.365529
19  Adventure      dragon  1.354445